### ISSUE TITLE
Tutorial keeps replaying

### ISSUE THREAD

**Issue by rauppe** [lopezbec/VR_SpatialVisualizationApp#10]
After challenges are complete they should be able to go back to Free View mode, currently, it returns to the tutorial and the user must iterate through the entire thing.

**Comment by Aidanjm13** [comment]
I have created a solution for this by leaving a dummy tutorial object active but not visible after it is run and the scene changes. When the user then returns to that scene, the new tutorial object that was created will first check to see if this dummy object exists, and if so the tutorial does not run.
