### ISSUE TITLE
Copy Rotation As To: Cannot complete

### ISSUE THREAD

**Issue by rauppe** [lopezbec/VR_SpatialVisualizationApp#4]
The first level doesn’t work unless the shape is changed (and then only rarely) and the second level appears to be unbeatable. Here is level one without changing the shape:

<img width="1512" alt="Screenshot 2023-10-27 at 2 21 09 PM" src="https://github.com/lopezbec/VR_SpatialVisualizationApp/assets/92817067/18cd3334-ef68-49a8-88db-d73405751270">

and level one with changing the shape:

<img width="1512" alt="Screenshot 2023-10-27 at 2 22 11 PM" src="https://github.com/lopezbec/VR_SpatialVisualizationApp/assets/92817067/f5d90ad1-4037-4245-b610-68b63108d922">

**Comment by Aidanjm13** [comment]
I haven't had issues beating this. I think the issue is that the first shape can achieve the same look with two different rotations.

**Comment by rauppe** [comment]
Thank you I was able to get it to work! You were right the rotations did look identical- had others try it and they couldn't get it correct either but it is working.
