### ISSUE TITLE
Copy Rotation As To: Changing Shapes

### ISSUE THREAD

**Issue by rauppe** [lopezbec/VR_SpatialVisualizationApp#5]
Users shouldn't be able to change the shapes with the number keys in Copy Rotation As To.

**Comment by Aidanjm13** [comment]
I have created a solution that allows the user to change the shape that they are using without affecting the shape of the object they are trying to copy. It also does not allow the user to switch to the same shape as the one they are trying to copy. This was done by disabling the script on the Match Objects ObjectManager, and by updating the ObjectManager script. The update allow another instance of ObjectManager to be referenced that it will not be able to copy the shape of.
I am new to using Github in this fashion, and am unsure as to how I should include these suggested changes.
