### ISSUE TITLE
Copy Rotation Hard, Unbeatable

### ISSUE THREAD

**Issue by rauppe** [lopezbec/VR_SpatialVisualizationApp#8]
The second level's picture is the same as the one for the first level- probably is a bug because the second level can't be beat by matching the picture.

<img width="1512" alt="Screenshot 2023-10-27 at 2 29 15 PM" src="https://github.com/lopezbec/VR_SpatialVisualizationApp/assets/92817067/bb412a84-d4ce-4dd2-a8ae-824505e78b8f">

**Comment by Aidanjm13** [comment]
I did not encounter this error when testing, could you please provide a video or elaborate?

**Comment by rauppe** [comment]
I reset my version of the project and pulled the latest version from git and it is working now- must have only been a problem on my end, thanks for checking it out!
